services:
  db:
    image: postgres:latest
    container_name: postgres_arenahub
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: arenahub
    ports:
      - '5432:5432'
    volumes:
      - arenahub_postgres_data:/var/lib/postgresql/data
    networks:
      - arenahubnetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_arenahub
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DOCKER_PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DOCKER_PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '15432:80'
    depends_on:
      - db
    networks:
      - arenahubnetwork

  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - "--no-cache"
    container_name: arenahub_app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/arenahub
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - '8080:8080'
      - '5005:5005'
    depends_on:
      - db
    networks:
      - arenahubnetwork

  proxy:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - arenahubnetwork

volumes:
  arenahub_postgres_data:

networks:
  arenahubnetwork:
    driver: bridge