server:
  tomcat:
    threads:
      max: 20
springdoc:
  server-url: https://arenahub-d665d54c598e.herokuapp.com
spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/alugai
    username: postgres
    password: 25052022
    hiraki:
      maximun-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: engstrategy05@gmail.com
    password: csrycjlmdxwswclg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      test-connection: true
zenvia:
  api-token: POz_IOVwRJaZhBPG1eyxQFyJ2BG5H9PBad3f
  sender-id: shard-vertebra
#jwt:
#    secret-key: ptw/PNIjH2BR2rjF4+1uRpv0V3oCRkxXNiZtnNU2rHEpM4iXBkUuWcDNSr+BuppztPEDvOgEp8vISdzPu+U2TQ==
