server:
  tomcat:
    threads:
      max: 20
springdoc:
  server-url: https://arenahub-d665d54c598e.herokuapp.com
arenahub:
  admin-email: saviosoares0402@gmail.com
spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/alugai
    username: postgres
    password: ${DATABASE_ARENAHUB_PASSWORD}
    hiraki:
      maximun-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: engstrategy05@gmail.com
    password: ${EMAIL_ENGSTRATEGY_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "smtp.gmail.com"
          localhost: "localhost"
        debug: false
zenvia:
  api-token: ${ZENVIA_API_TOKEN}
  sender-id: ${ZENVIA_SENDER_ID}
jwt:
  secret-key: ${JWT_SECRET_KEY_ARENAHUB}
logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration: ERROR