# =================================================
# SEÇÃO BASE - Carregada em TODOS os ambientes
# =================================================
app:
  frontend-url: ${ARENAHUB_FRONTEND_URL_LOCAL}
server:
  port: ${PORT:8080}
springdoc:
  server-url: ${ARENAHUB_BACKEND_URL_LOCAL}
arenahub:
  admin-email: ${ADMIN_EMAIL}
spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: arenahub.2025@gmail.com
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "smtp.gmail.com"

zenvia:
  api-token: ${ZENVIA_API_TOKEN}
  sender-id: ${ZENVIA_SENDER_ID}

jwt:
  secret-key: ${JWT_SECRET_KEY_ARENAHUB}

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration: ERROR
asaas:
  api:
    url: ${ASAAS_URL_SANDBOX}
    token: ${ASAAS_TOKEN_SANDBOX}

---
# =================================================
# PERFIL 'dev' - Para rodar localmente SEM Docker
# =================================================
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/arenahub
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
stripe:
  public-key: ${STRIPE_PUBLIC_KEY_TEST}
  secret-key: ${STRIPE_SECRET_KEY_TEST}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET_TEST}

---
# =================================================
# PERFIL 'docker' - Para rodar COM Docker Compose
# =================================================
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://db:5432/arenahub
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
stripe:
  public-key: ${STRIPE_PUBLIC_KEY_PROD}
  secret-key: ${STRIPE_SECRET_KEY_PROD}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET_PROD}