services:
  db:
    image: postgres:latest
    container_name: postgres_alugai
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alugai
    ports:
      - '5432:5432'
    volumes:
      - alugai_postgres_data:/var/lib/postgresql/data
    networks:
      - alugainetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_alugai
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '15432:80'
    depends_on:
      - db
    networks:
      - alugainetwork

volumes:
  alugai_postgres_data:

networks:
  alugainetwork:
    driver: bridge